# Template
# - name: proxmox
#   This will be the name of the service, and used for generating filename
#   domains: domain1.com,domain2.com
#   Comma separated list of domains for the service
#   urls: https://1.2.3.4, https://1.2.3.5
#   Comma separated list of services, used for load balancing if multiple provided

# Infrastructure
- name: proxmox
  domains: prx1.lab.ehcan.io
  urls: https://192.168.2.150:8006
- name: truenas
  domains: truenas.lab.ehcan.io
  urls: https://192.168.2.149
- name: synology
  domains: synology.lab.ehcan.io
  urls: https://192.168.2.148:5001

# Monitoring & Administration
- name: portainer
  domains: portainer.lab.ehcan.io
  urls: https://10.10.0.102:9443
- name: uptime-kuma-prx
  domains: uptime.lab.ehcan.io
  urls: http://10.10.0.102:3001
- name: uptime-kuma-truenas
  domains: uptime2.lab.ehcan.io, uptime-kuma-truenas.lab.ehcan.io
  urls: http://192.168.2.149:31050
- name: grafana
  domains: grafana.lab.ehcan.io
  urls: http://10.10.0.108:3000

# Media Stack
- name: arr_audiobookshelf
  domains: audiobookshelf.lab.ehcan.io, audiobookshelf.media.ehcan.io
  urls: http://10.10.0.102:13378
- name: arr_bazarr
  domains: bazarr.lab.ehcan.io, bazarr.media.ehcan.io
  urls: http://10.10.0.102:6767
- name: arr_lidarr
  domains: lidarr.lab.ehcan.io, lidarr.media.ehcan.io
  urls: http://10.10.0.102:8686
- name: arr_radarr
  domains: radarr.lab.ehcan.io, radarr.media.ehcan.io
  urls: http://10.10.0.102:7878
- name: arr_readarr
  domains: readarr.lab.ehcan.io, readarr.media.ehcan.io
  urls: http://10.10.0.102:8787
- name: arr_sonarr
  domains: sonarr.lab.ehcan.io, sonarr.media.ehcan.io
  urls: http://10.10.0.102:8989
- name: arr_prowlarr
  domains: prowlarr.lab.ehcan.io, prowlarr.media.ehcan.io
  urls: http://10.10.0.102:9696

- name: jellyfin
  domains: jellyfin.lab.ehcan.io, jellyfin.media.ehcan.io
  urls: http://10.10.0.101:8096
- name: jellyseerr
  domains: jellyseerr.lab.ehcan.io, jellyseerr.media.ehcan.io
  urls: http://10.10.0.102:5055

- name: metube
  domains: metube.lab.ehcan.io
  urls: http://10.10.0.102:8081

- name: syncthing-synology
  domains: syncthing.lab.ehcan.io
  urls: http://192.168.2.148:8384
- name: syncthing-prx
  domains: syncthing2.lab.ehcan.io
  urls: http://10.10.0.102:8384

# AI Services
- name: ai_litellm
  domains: litellm.lab.ehcan.io
  urls: http://10.10.0.102:4000
- name: ai_openwebui
  domains: ai.lab.ehcan.io
  urls: http://10.10.0.102:3300

# Apps & Utilities
- name: n8n
  domains: n8n.lab.ehcan.io
  urls: http://10.10.0.102:5678
- name: homarr
  domains: lab.ehcan.io
  urls: http://10.10.0.102:7575
- name: homeassistant
  domains: homeassistant.lab.ehcan.io
  urls: http://10.10.0.104:8123
- name: homebridge
  domains: homebridge.lab.ehcan.io
  urls: http://10.10.0.105:8581
